### ISSUE TITLE
Edge browser does not support fromEntries

### ISSUE THREAD

**Issue by rodriguez-facundo** [vasturiano/react-kapsule#1]
Hi 👋, `fromEntries` is not supported in microsoft Edge browser (I don't know if that is something important 🤣, but I drop the issue here just in case).

https://github.com/vasturiano/react-kapsule/blob/e780ad8d9e938722dd686050f71d8b3e2aa1b2d4/src/index.js#L35

**Comment by vasturiano** [comment]
Thanks @rodriguez-facundo. Just added a polyfill. 👍
