### ISSUE TITLE
Types declaration not valid in modern Typescript

### ISSUE THREAD

**Issue by mz8i** [vasturiano/react-kapsule#13]
On a project using typescript@5.5.3, when trying to use react-kapsule:
```
import fromKapsule from "react-kapsule";
```
the following error appears:
```
Could not find a declaration file for module 'react-kapsule'. The module implicitly has an 'any' type.
There are types at 'PATH-TO-REACT-KAPSULE/dist/react-kapsule.d.ts', but this result could not be resolved when respecting package.json "exports". The 'react-kapsule' library may need to update its package.json or typings.
```

See result of types config validation: https://arethetypeswrong.github.io/?p=react-kapsule%402.4.0
And also the corresponding explanation of the cause of the issue: https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/UntypedResolution.md

I am not exactly sure what the correct solution is, but it could seem from the linked docs that it will involve changing the extension to `index.d.mts`? But perhaps more steps are needed.

**Comment by vasturiano** [comment]
@mz8i thanks for reaching out. I think it just needed to be included in the `exports` section in `package.json`, which is now done. Error is gone:
https://arethetypeswrong.github.io/?p=react-kapsule%402.4.1
