### ISSUE TITLE
[Question] Listening to an event without consuming it

### ISSUE THREAD

**Issue by WhoAteDaCake** [vasturiano/react-kapsule#3]
Is there a way we have a function `onClick` on a component, without actually overriding logic of the component?

Example : [codesandbox](https://codesandbox.io/s/proud-cache-6tjry?fontsize=14&hidenavigation=1&theme=dark). Here we add onClick, but that removes the zoom functionality of the chart

**Comment by WhoAteDaCake** [comment]
I guess this is more of a `kapsule` question. My current approach was to add 

```javascript
    useImperativeHandle(ref, () => {
      return {
        getCore() {
          return comp;
        },
      };
    });
```

And doing `ref.current.getCore().focusOnNode(entry)` from the `onClick` handler

**Comment by vasturiano** [comment]
@WhoAteDaCake you don't have to go so far. If you register the react kapsule with a list of methods:
```
const Chart = fromKapsule(chartKapsule, {
  methodNames: ['focusOnNode']
})
``` 

the wrapper will do the `useImperativeHandle` work for you and expose the method, accessible like so:
```
ref.current.focusOnNode(...)
```
Then you can add that to the `onClick` handler if you wish.
